Adding csv check

diff --git a/scripts/accession_retrieve b/scripts/accession_retrieve
--- a/scripts/accession_retrieve
+++ b/scripts/accession_retrieve
@@ -36,6 +36,12 @@ pattern=' '
 SCRIPT_PATH="$CONDA_PREFIX/bin"
 DB_PATH='../../databases/'
 
+if [ ! -s "$CSV" ]
+then
+    echo "Error: CSV file required, if provided, check spelling"
+    exit 1
+fi
+
 i=1
 while IFS="," read INFILE JOB BLAST_DB SQLDB EVALUE MAX NUM_THREADS || [ -n "$INFILE$JOB$BLAST_DB$SQLDB$EVALUE$MAX$NUM_THREADS" ];
 do
@@ -48,17 +54,24 @@ do
     if [ -z "$INFILE" ] ||  [ -z "$JOB" ] || [ -z "$BLAST_DB" ] 
     then
         echo 'Fasta_file, job_name and BLAST_database_name are required arguments'
+        exit 1
     fi
 
     if [[ "$INFILE" =~ ^[0-9] ]] || [[ "$JOB" =~ ^[0-9] ]] || [[ "$BLAST_DB" =~ ^[0-9] ]] || [[ "$SQLDB" =~ ^[0-9] ]];
     then
-        echo 'Paramaeters cannot start with a number'
+        echo 'Fasta_file, job_name, BLAST_database_name and SQLite3_db cannot start with a number'
         exit 1
     fi
 
     if [[ "$BLAST_DB" =~ $pattern ]] || [[ "$SQLDB" =~ $pattern ]];
     then
         echo 'BLAST_database and SQLite3_db cannot contain spaces, please replace with _'
+        exit 1
+    fi
+
+    if [ ! -s "$INFILE" ]
+    then
+        echo "Error: Cannot find Fasta_file"
         exit 1
     fi
 
diff --git a/scripts/aliasdb_pipeline b/scripts/aliasdb_pipeline
--- a/scripts/aliasdb_pipeline
+++ b/scripts/aliasdb_pipeline
@@ -31,6 +31,12 @@ done
 pattern=' '
 SCRIPT_PATH="$CONDA_PREFIX/bin"
 
+if [ ! -s "$CSV" ]
+then
+    echo "Error: CSV file required, if provided, check spelling"
+    exit 1
+fi
+
 i=1
 while IFS="," read DBLIST DBTYPE TITLE OUTPUT SQLDB || [ -n "$DBLIST$DBTYPE$TITLE$OUTPUT$SQLDB" ];
 do
@@ -40,7 +46,7 @@ do
 
 
     # Make sure required arguments are supplied    
-    if [ -z "$DBLIST" ] ||  [ -z "$DBTYPE" ] || [ -z "$TITLE" ] || [ -z "$OUTPUT" ] 
+    if [ ! -s "$DBLIST" ] ||  [ -z "$DBTYPE" ] || [ -z "$TITLE" ] || [ -z "$OUTPUT" ] 
     then
         echo 'dblist_file, dbtype, title, output are required arguments'
         exit 1
diff --git a/scripts/delete_db b/scripts/delete_db
--- a/scripts/delete_db
+++ b/scripts/delete_db
@@ -31,6 +31,12 @@ done
 pattern=' '
 SCRIPT_PATH="$CONDA_PREFIX/bin"
 
+if [ ! -s "$CSV" ]
+then
+    echo "Error: CSV file required, if provided, check spelling"
+    exit 1
+fi
+
 i=1
 while IFS="," read BLASTDB SQLDB || [ -n "$BLASTDB$SQLDB" ];
 do
diff --git a/scripts/orthology_pipeline b/scripts/orthology_pipeline
--- a/scripts/orthology_pipeline
+++ b/scripts/orthology_pipeline
@@ -18,6 +18,7 @@ while :; do
         echo "                                csv must be in format: JOB_NAME, ACCESSION_LIST, FB_DATABASE, RB_DATABASE, EVALUE, HITS, COVERAGE, SQLITE3_DB, NUM_THREADS, MAX, TREE, FREQUENCY, MODEL"
         echo "                                The following fields are optional, defualt values are shown, all other fields are required:"
         echo "                                SQLITE3_DB: SQLite3 database, default = accession_db.db"
+        echo "                                EVALUE: expect value, default = 0.1"
         echo "                                NUM_THREADS: int, number of threads to use, default = 4"
       	echo "                                MAX: int, maximum number of sequences to retrieve in BLAST, default = 150"
         echo "                                TREE: boolean (y/n), perform phylogenetic analysis, default = n"
@@ -37,6 +38,12 @@ pattern=' '
 DB_PATH='../../databases/'
 SCRIPT_PATH="$CONDA_PREFIX/bin"
 
+if [ ! -s "$CSV" ]
+then
+    echo "Error: CSV file required, if provided, check spelling"
+    exit 1
+fi
+
 i=1
 while IFS="," read  NAME INPUT FBLAST_DB RBLAST_DB EVALUE HITS COV SQLDB NUM_THREADS MAX_HITS TREE FREQ MODEL|| [ -n "$NAME$INPUT$FBLAST_DB$RBLAST_DB$EVALUE$HITS$COV$SQLDB$NUM_THREADS$MAX_HITS$TREE$FREQ$MODEL" ];
 do
@@ -46,9 +53,10 @@ do
     MODEL=$(echo $MODEL | tr -d '\r')
 
     #Validating inputs   
-    if [ -z "$NAME" ] || [ -z "$INPUT" ] || [ -z "$FBLAST_DB" ] || [ -z "$RBLAST_DB" ] || [ -z "$HITS" ] || [ -z "$COV" ]; 
+    if [ -z "$NAME" ] || [ ! -s "$INPUT" ] || [ -z "$FBLAST_DB" ] || [ -z "$RBLAST_DB" ] || [ -z "$HITS" ] || [ -z "$COV" ]; 
     then
-        echo 'Job_name, Accession_list, FB_database, RB_database, Hits and Coverage are required arguments'        
+        echo 'Job_name, Accession_list, FB_database, RB_database, Hits and Coverage are required arguments'
+        echo 'Ensure Accession_list file present, correctly spelt and includes extension'        
         exit 1
     fi
     
